// Coordination metadata — turn a gap list into a plan someone can actually execute.
//
// The assessment already answers "what is broken" and "why it matters" (shared/requirements.ts
// REQUIREMENT_GUIDANCE) and "what to do about it" (`fix`). What it did NOT answer is the set of
// questions that actually decide whether a dealership closes the gap:
//
//    Who owns this?  Which outside party must participate?  How much work is it?
//    What artifact proves it is done?  What happens operationally if it slips?
//    What can realistically be finished in the next 30 days?
//
// Compliance programs usually fail as a COORDINATION problem, not a knowledge problem: the GM
// says it belongs to IT, IT says the DMS vendor owns it, the vendor says it is a policy
// question, and nothing moves. This module encodes the routing so the product ships a plan
// rather than a finding list.
//
// Pure, dependency-free, and authored (mirrors REQUIREMENT_GUIDANCE): keyed by requirement code,
// consumed by shared/task-derivation.ts and rendered by the Dashboard / Tasks board. Never
// generated by an LLM, and never used to decide pass/fail — status stays deterministic in
// shared/derivation.ts.

/** Task priority enum, matching drizzle/schema.ts taskPriorityEnum.
 *  Declared HERE rather than in task-derivation.ts so this module has no imports at all:
 *  task-derivation imports coordination, and a back-import would make the pair cyclic. The
 *  Deno edge runtime resolves these modules live rather than bundling them, so the dependency
 *  is kept strictly one-directional. task-derivation re-exports this for its existing callers. */
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';

/** Who inside the dealership is accountable for closing the gap. */
export type OwnerRole =
  | 'ownership'
  | 'qualified_individual'
  | 'gm_controller'
  | 'it_msp'
  | 'hr_training';

/** Which outside party must participate for the work to complete (null = fully internal). */
export type VendorParty = 'dms' | 'msp' | 'security_firm' | 'counsel' | null;

/** Rough size of the work — drives sequencing, not scoring. */
export type Effort = 'quick' | 'moderate' | 'project';

/** Planning horizon in days: what to do now / next / after that. */
export type Horizon = 30 | 60 | 90;

export interface Coordination {
  /** The accountable internal owner. One role — shared ownership is how gaps stall. */
  owner: OwnerRole;
  /** The outside party whose participation is required, if any. */
  vendor: VendorParty;
  effort: Effort;
  /** The artifact that proves this is closed — what to upload to Evidence. */
  proof: string;
  /** The operational consequence of delay, in dealership terms (not penalty theatre). */
  consequence: string;
}

export const OWNER_LABEL: Record<OwnerRole, string> = {
  ownership: 'Dealer principal / owner',
  qualified_individual: 'Qualified Individual',
  gm_controller: 'GM / Controller',
  it_msp: 'IT provider / MSP',
  hr_training: 'HR / training manager',
};

export const VENDOR_LABEL: Record<Exclude<VendorParty, null>, string> = {
  dms: 'DMS vendor',
  msp: 'IT provider / MSP',
  security_firm: 'Third-party security testing firm',
  counsel: 'Outside counsel',
};

export const EFFORT_LABEL: Record<Effort, string> = {
  quick: 'Under a day',
  moderate: '1–2 weeks',
  project: '30+ days / recurring',
};

/** Fallback for a requirement with no authored entry: honest about not knowing rather than
 *  inventing an owner. Kept in sync with the catalog by server/coordination.test.ts. */
export const COORDINATION_FALLBACK: Coordination = {
  owner: 'qualified_individual',
  vendor: null,
  effort: 'moderate',
  proof: 'Documentation showing the control is in place, dated and retained.',
  consequence: 'This gap stays unowned until someone is named against it.',
};

// One entry per requirement code (all 45). Authored, grounded in how a franchised dealership
// actually operates: the QI owns the program, the MSP owns the technical controls, the GM and
// controller own the process controls, HR owns training, and the DMS vendor has to be in the
// room for anything touching the system of record.
export const COORDINATION_BY_CODE: Record<string, Coordination> = {
  // §314.4(a)/(i) — Qualified Individual
  q1_1: {
    owner: 'ownership',
    vendor: null,
    effort: 'quick',
    proof: 'Signed designation naming the Qualified Individual, with the effective date.',
    consequence:
      'Until someone is named, every other gap on this list has no owner — work bounces between the GM, IT, and the DMS vendor and nothing closes.',
  },
  q1_2: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: "A one-page summary of the QI's certifications, training, and relevant experience.",
    consequence:
      'A QI who cannot show relevant background is the first thing an examiner or a cyber-insurance underwriter challenges, and the designation stops carrying weight.',
  },
  q1_3: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'A calendared annual reporting date plus the most recent written report to ownership.',
    consequence:
      'Without a standing report to ownership, security spending competes ad hoc against every other request and usually loses.',
  },
  q1_4: {
    owner: 'ownership',
    vendor: null,
    effort: 'quick',
    proof: "A written QI charter stating the role's authority and duties, approved by ownership.",
    consequence:
      "During an incident, an unwritten charter means the QI has to ask permission for decisions that need to be made in minutes.",
  },
  q1_5: {
    owner: 'ownership',
    vendor: null,
    effort: 'quick',
    proof: 'A named backup or documented succession path for the QI role.',
    consequence:
      'One resignation puts the whole program on hold, usually discovered only when the next assessment or incident arrives.',
  },

  // §314.4(b) — Risk assessment
  q2_1: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'moderate',
    proof: 'The written risk assessment document, dated and covering every system holding NPI.',
    consequence:
      'Without it, safeguards spending is guesswork — you cannot show why you bought what you bought, or defend what you skipped.',
  },
  q2_2: {
    owner: 'qualified_individual',
    vendor: 'msp',
    effort: 'moderate',
    proof: 'The threat section of the risk assessment, listing internal and external threats.',
    consequence:
      'Threats you never wrote down are the ones no control was ever assigned to.',
  },
  q2_3: {
    owner: 'qualified_individual',
    vendor: 'msp',
    effort: 'moderate',
    proof: 'A per-system vulnerability list with the control gap identified for each.',
    consequence:
      'A risk assessment with no vulnerability detail produces no remediation list — it reads well and changes nothing.',
  },
  q2_4: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'A recurring annual review date plus the dated record of the last review.',
    consequence:
      'A stale assessment describes a dealership you no longer operate, so the program drifts out of alignment with the actual systems.',
  },
  q2_5: {
    owner: 'qualified_individual',
    vendor: 'dms',
    effort: 'quick',
    proof: 'A written trigger rule tying system changes (DMS migration, new integration) to a reassessment.',
    consequence:
      'DMS migrations and new integrations are exactly when exposure changes; without a trigger, the change lands and nobody reassesses until next year.',
  },

  // §314.4(c)(2)/(c)(6) — Data inventory, retention, disposal
  q3_1: {
    owner: 'qualified_individual',
    vendor: 'dms',
    effort: 'moderate',
    proof: 'A data inventory listing every store of customer NPI, including backups and vendor systems.',
    consequence:
      'Unmapped NPI is the part of a breach you discover during the breach — and it is what makes notification scope impossible to bound.',
  },
  q3_2: {
    owner: 'gm_controller',
    vendor: null,
    effort: 'moderate',
    proof: 'A written retention schedule stating how long each NPI type is kept and when it is destroyed.',
    consequence:
      'Deal jackets and credit apps accumulate indefinitely, so every year of retained data enlarges the next incident for no business benefit.',
  },
  q3_3: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'moderate',
    proof: 'A list of every third party receiving NPI and the agreement governing that sharing.',
    consequence:
      'Undocumented data sharing means you cannot answer the first question after a vendor breach: was our data in it?',
  },
  q3_4: {
    owner: 'gm_controller',
    vendor: null,
    effort: 'quick',
    proof: 'The written disposal procedure plus a shredding/media-destruction certificate.',
    consequence:
      'Paper deal jackets and retired hard drives leave the building intact — an avoidable and very visible failure.',
  },
  q3_5: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'A scheduled inventory review date plus the dated record of the last refresh.',
    consequence:
      'The inventory silently loses coverage as systems change, so controls get applied to a map that no longer matches the territory.',
  },

  // §314.4(c)(1)/(c)(5)/(c)(8) — Access controls
  q4_1: {
    owner: 'it_msp',
    vendor: 'dms',
    effort: 'moderate',
    proof: 'An MFA enforcement report or policy screenshot covering every system that reaches NPI.',
    consequence:
      'This is the single control most likely to stop a real account takeover, and the one an insurer is most likely to ask about at renewal.',
  },
  q4_2: {
    owner: 'it_msp',
    vendor: 'dms',
    effort: 'moderate',
    proof: 'A role-to-permission mapping showing what each dealership role can reach.',
    consequence:
      'When every service writer has F&I-level visibility, one compromised login exposes far more customer data than the role ever needed.',
  },
  q4_3: {
    owner: 'gm_controller',
    vendor: 'msp',
    effort: 'quick',
    proof: 'A written offboarding checklist plus evidence of access revocation for a recent departure.',
    consequence:
      'Dealership turnover is high; without a revocation step tied to the last day, former staff keep DMS access for months.',
  },
  q4_4: {
    owner: 'it_msp',
    vendor: null,
    effort: 'moderate',
    proof: 'Logging configuration plus a sample review of privileged-account activity.',
    consequence:
      'Administrative misuse leaves no trace, so an internal incident becomes unprovable in either direction.',
  },
  q4_5: {
    owner: 'qualified_individual',
    vendor: 'dms',
    effort: 'quick',
    proof: 'A signed quarterly access review showing accounts reviewed and entitlements removed.',
    consequence:
      'Access only accumulates. Without a review cadence, permissions granted for one busy weekend stay forever.',
  },

  // §314.4(c)(3) — Encryption
  q5_1: {
    owner: 'it_msp',
    vendor: 'dms',
    effort: 'project',
    proof: 'Encryption-at-rest confirmation for each NPI store, including the DMS vendor’s written attestation.',
    consequence:
      'A stolen backup or a retired server becomes a reportable event instead of a non-event.',
  },
  q5_2: {
    owner: 'it_msp',
    vendor: null,
    effort: 'moderate',
    proof: 'TLS configuration evidence for every connection carrying NPI.',
    consequence:
      'Data moving between the store, the DMS, and lenders is exposed on any network you do not control.',
  },
  q5_3: {
    owner: 'it_msp',
    vendor: null,
    effort: 'moderate',
    proof: 'A written key-management procedure covering storage, access, and rotation.',
    consequence:
      'Encryption that everyone can unlock is documentation, not a control.',
  },
  q5_4: {
    owner: 'gm_controller',
    vendor: 'msp',
    effort: 'moderate',
    proof: 'Secure-email or portal configuration plus the staff instruction for sending NPI.',
    consequence:
      'Credit apps and driver’s licenses get emailed in plain text daily — the highest-volume leak path in a dealership.',
  },
  q5_5: {
    owner: 'it_msp',
    vendor: null,
    effort: 'moderate',
    proof: 'A device-encryption report covering laptops, tablets, and phones that reach NPI.',
    consequence:
      'A laptop left in a demo vehicle turns into a breach rather than a hardware replacement.',
  },

  // §314.4(f) — Service providers
  q6_1: {
    owner: 'ownership',
    vendor: 'counsel',
    effort: 'project',
    proof: 'Executed contracts or addenda specifying the security controls each vendor must maintain.',
    consequence:
      'Without contractual terms you carry the vendor’s risk with no recourse when they cause the incident.',
  },
  q6_2: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'moderate',
    proof: 'A dated vendor assessment (questionnaire, SOC 2, or attestation) for each critical vendor.',
    consequence:
      'A vendor that was secure at signing quietly degrades, and you find out when they do.',
  },
  q6_3: {
    owner: 'ownership',
    vendor: 'counsel',
    effort: 'moderate',
    proof: 'Contract language requiring breach notification to you within a defined window.',
    consequence:
      'You cannot meet your own notification duty if the vendor tells you months late — their delay becomes your exposure.',
  },
  q6_4: {
    owner: 'qualified_individual',
    vendor: 'dms',
    effort: 'moderate',
    proof: 'A completed security assessment of the DMS vendor, with their responses retained.',
    consequence:
      'The DMS holds the largest single concentration of customer NPI in the store; unassessed, it is the biggest unknown in the program.',
  },
  q6_5: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'moderate',
    proof: 'A written monitoring process plus the record of the most recent vendor check.',
    consequence:
      'Contract terms nobody verifies produce paper compliance and real exposure.',
  },

  // §314.4(h) — Incident response
  q7_1: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'moderate',
    proof: 'The written incident response plan, dated and distributed to the response team.',
    consequence:
      'Without a plan, the first hour of an incident is spent deciding who to call instead of containing it.',
  },
  q7_2: {
    owner: 'qualified_individual',
    vendor: 'msp',
    effort: 'moderate',
    proof: 'A dated tabletop exercise record with the findings and the fixes made.',
    consequence:
      'An untested plan fails on first use, usually on the parts nobody thought to check — contact lists and vendor escalation paths.',
  },
  q7_3: {
    owner: 'qualified_individual',
    vendor: 'counsel',
    effort: 'moderate',
    proof: 'The breach-notification procedure with named owners and the notification timeline.',
    consequence:
      'Notification deadlines run whether or not you have a procedure; improvising them compounds the original incident.',
  },
  q7_4: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'A named incident response team roster with each member’s role and decision authority.',
    consequence:
      'Unclear authority means containment decisions wait for the owner to be reachable.',
  },
  q7_5: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'An incident log with entries for handling and resolution (empty is fine if dated and maintained).',
    consequence:
      'No log means no evidence trail — and no way to show a pattern was addressed rather than repeated.',
  },

  // §314.4(e)(1) — Personnel / training
  q8_1: {
    owner: 'hr_training',
    vendor: null,
    effort: 'moderate',
    proof: 'A training completion report covering all staff, with dates.',
    consequence:
      'Staff are the most-targeted surface in a dealership; untrained personnel are where most real incidents start.',
  },
  q8_2: {
    owner: 'hr_training',
    vendor: 'msp',
    effort: 'moderate',
    proof: 'Phishing simulation results with the follow-up training assigned.',
    consequence:
      'Without practice you learn who clicks from the actual attacker.',
  },
  q8_3: {
    owner: 'hr_training',
    vendor: null,
    effort: 'quick',
    proof: 'An onboarding checklist item requiring security training before system access is granted.',
    consequence:
      'New hires get DMS credentials on day one and guidance weeks later — the riskiest window in the employment cycle.',
  },
  q8_4: {
    owner: 'hr_training',
    vendor: null,
    effort: 'quick',
    proof: 'Retained training records showing who completed what, and when.',
    consequence:
      'Training that happened but was never recorded is training you cannot prove happened.',
  },
  q8_5: {
    owner: 'hr_training',
    vendor: null,
    effort: 'quick',
    proof: 'The training curriculum showing social-engineering and pretexting content.',
    consequence:
      'Dealerships get called by fake lenders, fake vendors, and fake buyers; staff who cannot recognize it hand over data willingly.',
  },

  // §314.4(d) — Testing and monitoring
  q9_1: {
    owner: 'qualified_individual',
    vendor: 'security_firm',
    effort: 'project',
    proof: 'The annual penetration test report from a qualified third party.',
    consequence:
      'You are relying on the assumption that controls work, with nothing that has ever tried to break them.',
  },
  q9_2: {
    owner: 'it_msp',
    vendor: 'msp',
    effort: 'moderate',
    proof: 'Vulnerability scan reports at least every six months, with remediation notes.',
    consequence:
      'Newly disclosed vulnerabilities sit unpatched in the window between scans that never happen.',
  },
  q9_3: {
    owner: 'it_msp',
    vendor: 'msp',
    effort: 'project',
    proof: 'Monitoring/SIEM configuration plus a sample alert review.',
    consequence:
      'Intrusions run for months undetected; continuous monitoring is also the Rule’s alternative to annual pen testing.',
  },
  q9_4: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'A vulnerability tracker showing findings with owners and target dates.',
    consequence:
      'Findings that are not tracked to closure quietly persist and reappear in the next report.',
  },
  q9_5: {
    owner: 'qualified_individual',
    vendor: null,
    effort: 'quick',
    proof: 'The QI’s dated review of test results and the remediation direction given.',
    consequence:
      'Test results that never reach the accountable owner change nothing and never make the board report.',
  },
};

/** Coordination for a requirement code, falling back honestly rather than fabricating. */
export function getCoordination(code: string): Coordination {
  return COORDINATION_BY_CODE[code] ?? COORDINATION_FALLBACK;
}

/**
 * Planning horizon for a piece of remediation — "what can be done in the next 30 days".
 *
 * Deterministic matrix over (priority, effort). EFFORT DOMINATES, deliberately: 23 of the 45
 * requirements carry the `critical` scoring weight, so sequencing on urgency alone puts ~31
 * items in the first 30 days, which is not a plan — it is the same undifferentiated gap list
 * with a deadline on it. Promising more than a month can hold is exactly how a remediation
 * roadmap loses credibility on first review.
 *
 * So the 30-day bucket holds only work that is BOTH urgent and genuinely short (under a day),
 * which is also the right behavioural bias: a store that closes fifteen small items in month
 * one keeps going. Nothing critical is ever parked past 60 days.
 */
export function horizonFor(priority: TaskPriority, effort: Effort): Horizon {
  if (priority === 'critical') return effort === 'quick' ? 30 : 60;
  if (priority === 'high') return effort === 'quick' ? 30 : 90;
  return effort === 'quick' ? 60 : 90;
}

export const HORIZON_LABEL: Record<Horizon, string> = {
  30: 'Next 30 days',
  60: 'Days 31–60',
  90: 'Days 61–90',
};

/** One-line routing summary: who owns it, who else has to be in the room. */
export function participantsLine(coordination: Coordination): string {
  const owner = OWNER_LABEL[coordination.owner];
  if (!coordination.vendor) return `${owner} (internal — no outside party required)`;
  return `${owner}, with ${VENDOR_LABEL[coordination.vendor]}`;
}
