// Coordination metadata — turn a gap list into a plan someone can actually execute.
//
// The assessment already answers "what is broken" and "why it matters" (shared/requirements.ts
// REQUIREMENT_GUIDANCE) and "what to do about it" (`fix`). What it did NOT answer is the set of
// questions that actually decide whether a dealership closes the gap:
//
//    Who owns this?  How much work is it?  What artifact proves it is done?
//    What is the exposure if it slips?  What can realistically be finished in 30 days?
//
// Compliance programs usually fail as a COORDINATION problem, not a knowledge problem: the GM
// says it belongs to IT, IT says it is a policy question, and nothing moves. This module encodes
// the routing so the product ships a plan rather than a finding list.
//
// Pure, dependency-free, and authored (mirrors REQUIREMENT_GUIDANCE): keyed by requirement code,
// consumed by shared/task-derivation.ts, shared/pdf-generator.ts, and the Dashboard / Tasks /
// Summary surfaces. Never generated by an LLM, and never used to decide pass/fail — status stays
// deterministic in shared/derivation.ts.
//
// TWO DELIBERATE CALLS, both confirmed against dealership operating experience (2026-07-29):
//
//  1. NO VENDOR-PARTICIPATION FIELD. An earlier draft flagged which outside party (DMS vendor,
//     MSP, counsel) had to be involved. It was removed: in practice a named outside dependency
//     reads as a ready-made reason to defer, and the dealership owns the obligation under the
//     Rule regardless of who it delegates the work to. Every item here is internally owned.
//
//  2. CONSEQUENCES ARE FRAMED AS REGULATORY EXPOSURE, not operational inconvenience. Enforcement
//     is what actually moves a dealer principal to spend. But this is scoped strictly to the
//     `consequence` lines — the Dashboard and landing-page copy stay calibrated and non-alarmist
//     on purpose. Each line stays grounded in the Rule's own text (what §314.4 makes mandatory,
//     what an examiner requests first). No invented penalty figures, no speculative enforcement
//     claims — the same evidentiary bar as every other authored string in this codebase.

/** Task priority enum, matching drizzle/schema.ts taskPriorityEnum.
 *  Declared HERE rather than in task-derivation.ts so this module has no imports at all:
 *  task-derivation imports coordination, and a back-import would make the pair cyclic. The
 *  Deno edge runtime resolves these modules live rather than bundling them, so the dependency
 *  is kept strictly one-directional. task-derivation re-exports this for its existing callers. */
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';

/** Who inside the dealership is accountable for closing the gap. */
export type OwnerRole =
  | 'ownership'
  | 'qualified_individual'
  | 'gm_controller'
  | 'it_msp'
  | 'hr_training';

/** Rough size of the work — drives sequencing, not scoring. */
export type Effort = 'quick' | 'moderate' | 'project';

/** Planning horizon in days: what to do now / next / after that. */
export type Horizon = 30 | 60 | 90;

export interface Coordination {
  /** The accountable internal owner. One role — shared ownership is how gaps stall. */
  owner: OwnerRole;
  effort: Effort;
  /** The artifact that proves this is closed — what to upload to Evidence. */
  proof: string;
  /** The regulatory exposure created by leaving this open (see note 2 in the header). */
  consequence: string;
}

export const OWNER_LABEL: Record<OwnerRole, string> = {
  ownership: 'Dealer principal / owner',
  qualified_individual: 'Qualified Individual',
  gm_controller: 'GM / Controller',
  it_msp: 'IT provider / MSP',
  hr_training: 'HR / training manager',
};

export const EFFORT_LABEL: Record<Effort, string> = {
  quick: 'Under a day',
  moderate: '1–2 weeks',
  project: '30+ days / recurring',
};

/** Fallback for a requirement with no authored entry: honest about not knowing rather than
 *  inventing an owner. Kept in sync with the catalog by server/coordination.test.ts. */
export const COORDINATION_FALLBACK: Coordination = {
  owner: 'qualified_individual',
  effort: 'moderate',
  proof: 'Documentation showing the control is in place, dated and retained.',
  consequence: 'This gap stays unowned until someone is named against it.',
};

// One entry per requirement code (all 45). Authored, grounded in how a franchised dealership
// actually operates: the QI owns the program, the MSP owns the technical controls, the GM and
// controller own the process controls, and HR owns training.
export const COORDINATION_BY_CODE: Record<string, Coordination> = {
  // §314.4(a)/(i) — Qualified Individual
  q1_1: {
    owner: 'ownership',
    effort: 'quick',
    proof: 'Signed designation naming the Qualified Individual, with the effective date.',
    consequence:
      'Designating a Qualified Individual is mandatory under §314.4(a) and is the first thing an examiner asks to see. With no named QI there is no program of record, and every other finding on this list is unowned.',
  },
  q1_2: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: "A one-page summary of the QI's certifications, training, and relevant experience.",
    consequence:
      'The Rule requires the individual to be *qualified*, not merely designated. A QI who cannot evidence relevant background invites a challenge to the entire program, and cyber-insurance underwriters ask the same question at renewal.',
  },
  q1_3: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'A calendared annual reporting date plus the most recent written report to ownership.',
    consequence:
      '§314.4(i) makes the QI\'s written report to the board or governing body a standing obligation. A missing report is a discrete, easily proven violation — there is no partial credit for having meant to write one.',
  },
  q1_4: {
    owner: 'ownership',
    effort: 'quick',
    proof: "A written QI charter stating the role's authority and duties, approved by ownership.",
    consequence:
      "Without a charter you cannot demonstrate the QI actually has authority to run the program, which undercuts the §314.4(a) designation itself and leaves containment decisions waiting on the owner during an incident.",
  },
  q1_5: {
    owner: 'ownership',
    effort: 'quick',
    proof: 'A named backup or documented succession path for the QI role.',
    consequence:
      'The §314.4(a) obligation does not pause when the QI resigns. A vacant QI role means the program is formally unstaffed, usually discovered at the worst possible moment.',
  },

  // §314.4(b) — Risk assessment
  q2_1: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'The written risk assessment document, dated and covering every system holding NPI.',
    consequence:
      '§314.4(b)(1) requires the risk assessment to be *written*. It is the document an examiner requests first, because the whole program is required to be based on it — without one, every safeguard you have is unjustified on paper.',
  },
  q2_2: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'The threat section of the risk assessment, listing internal and external threats.',
    consequence:
      '§314.4(b)(1) prescribes the assessment\'s required contents, including internal and external threats. An assessment missing them is incomplete on its face and fails the element even though a document exists.',
  },
  q2_3: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'A per-system vulnerability list with the control gap identified for each.',
    consequence:
      'The Rule requires assessment of the sufficiency of existing safeguards. A risk assessment with no vulnerability detail produces no remediation record, so there is nothing to show an examiner that findings were ever acted on.',
  },
  q2_4: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'A recurring annual review date plus the dated record of the last review.',
    consequence:
      '§314.4(b)(2) requires periodic reassessment. A stale assessment is a live violation of a mandatory element, and the date on the document is the easiest thing in the program to check.',
  },
  q2_5: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'A written trigger rule tying system changes (DMS migration, new integration) to a reassessment.',
    consequence:
      '§314.4(b)(2) requires reassessment on material change, not only on a calendar. A DMS migration or new integration without a documented reassessment is a gap an examiner can date precisely.',
  },

  // §314.4(c)(2)/(c)(6) — Data inventory, retention, disposal
  q3_1: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'A data inventory listing every store of customer NPI, including backups and vendor systems.',
    consequence:
      '§314.4(c)(2) requires you to know where customer information is collected, stored, and transmitted. Unmapped NPI also makes breach-notification scope impossible to bound, which converts one incident into an open-ended obligation.',
  },
  q3_2: {
    owner: 'gm_controller',
    effort: 'moderate',
    proof: 'A written retention schedule stating how long each NPI type is kept and when it is destroyed.',
    consequence:
      '§314.4(c)(6) requires periodic review of data retention. Deal jackets and credit applications retained without a schedule enlarge every future incident and are trivially evidenced against you.',
  },
  q3_3: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'A list of every third party receiving NPI and the agreement that governs that sharing.',
    consequence:
      'Undocumented data sharing means you cannot answer the first question after a third-party breach — was our data in it? — and cannot demonstrate the §314.4(f) oversight the Rule requires.',
  },
  q3_4: {
    owner: 'gm_controller',
    effort: 'quick',
    proof: 'The written disposal procedure plus a shredding/media-destruction certificate.',
    consequence:
      '§314.4(c)(6) requires secure disposal of customer information. Recoverable data on discarded paper or media is a documented failure of a mandatory element, and a visible one.',
  },
  q3_5: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'A scheduled inventory review date plus the dated record of the last refresh.',
    consequence:
      'An inventory that is not maintained stops satisfying §314.4(c)(2) as systems change, so controls end up applied to a map that no longer matches the dealership.',
  },

  // §314.4(c)(1)/(c)(5)/(c)(8) — Access controls
  q4_1: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'An MFA enforcement report or policy screenshot covering every system that reaches NPI.',
    consequence:
      'Multi-factor authentication is explicitly mandatory under §314.4(c)(5). It is the single most-cited Safeguards deficiency, the control insurers ask about first at renewal, and there is no risk-based argument for omitting it.',
  },
  q4_2: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'A role-to-permission mapping showing what each dealership role can reach.',
    consequence:
      '§314.4(c)(1) requires access limited to what each role needs. Broad DMS entitlements are easy for an examiner to sample and hard to justify after the fact.',
  },
  q4_3: {
    owner: 'gm_controller',
    effort: 'quick',
    proof: 'A written offboarding checklist plus evidence of access revocation for a recent departure.',
    consequence:
      'Periodic review of access privileges is required under §314.4(c)(1). Given dealership turnover, active credentials for departed staff are among the most reliably findable deficiencies in a store.',
  },
  q4_4: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'Logging configuration plus a sample review of privileged-account activity.',
    consequence:
      '§314.4(c)(8) requires monitoring and logging of authorized-user activity. Without logs you cannot evidence the control, and an internal incident becomes unprovable in either direction.',
  },
  q4_5: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'A signed quarterly access review showing accounts reviewed and entitlements removed.',
    consequence:
      '§314.4(c)(1) requires periodic review, and the review record is the evidence. Access only accumulates, so a missing cadence is both a violation and a growing exposure.',
  },

  // §314.4(c)(3) — Encryption
  q5_1: {
    owner: 'it_msp',
    effort: 'project',
    proof: 'Encryption-at-rest confirmation for each NPI store, including a written vendor attestation.',
    consequence:
      '§314.4(c)(3) requires encryption of customer information at rest. Where it is infeasible the Rule demands the QI approve a written compensating control — an undocumented exception is simply a failed element.',
  },
  q5_2: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'TLS configuration evidence for every connection carrying NPI.',
    consequence:
      '§314.4(c)(3) covers customer information in transit as well as at rest. Unencrypted transmission between the store, the DMS, and lenders is a direct failure of a mandatory element.',
  },
  q5_3: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'A written key-management procedure covering storage, access, and rotation.',
    consequence:
      'Encryption that everyone can unlock does not evidence the §314.4(c)(3) control. Without key management you cannot show the safeguard is effective, only that it is configured.',
  },
  q5_4: {
    owner: 'gm_controller',
    effort: 'moderate',
    proof: 'Secure-email or portal configuration plus the staff instruction for sending NPI.',
    consequence:
      'Emailing credit applications and licences in plain text is unencrypted transmission of customer information under §314.4(c)(3) — and it is the highest-volume, easiest-to-sample violation in a dealership.',
  },
  q5_5: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'A device-encryption report covering laptops, tablets, and phones that reach NPI.',
    consequence:
      'An unencrypted lost device is both a §314.4(c)(3) failure and, depending on the data, a notifiable event — device encryption is what keeps a hardware loss from becoming a reportable breach.',
  },

  // §314.4(f) — Service providers
  q6_1: {
    owner: 'ownership',
    effort: 'project',
    proof: 'Executed contracts or addenda specifying the security controls each provider must maintain.',
    consequence:
      '§314.4(f)(2) requires you to contractually obligate service providers to implement and maintain safeguards. A contract without those terms is a documented failure that sits in your own filing cabinet.',
  },
  q6_2: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'A dated vendor assessment (questionnaire, SOC 2, or attestation) for each critical provider.',
    consequence:
      '§314.4(f)(3) requires periodic assessment of service providers based on the risk they present. Selecting a capable provider once does not discharge the ongoing obligation.',
  },
  q6_3: {
    owner: 'ownership',
    effort: 'moderate',
    proof: 'Contract language requiring breach notification to you within a defined window.',
    consequence:
      'Your §314.4(h) response duties and the §314.4(j) notification clock run regardless of when a provider tells you. Without a contractual window, their delay becomes your missed deadline.',
  },
  q6_4: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: "A completed security assessment of the DMS provider's safeguards, with responses retained.",
    consequence:
      'The DMS holds the largest concentration of customer NPI in the store, so §314.4(f)(3) oversight of it carries the most weight — and its absence is the most consequential gap in the vendor element.',
  },
  q6_5: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'A written monitoring process plus the record of the most recent provider check.',
    consequence:
      '§314.4(f) requires oversight, not just paperwork at signing. Contract terms nobody verifies produce documented compliance and undocumented risk.',
  },

  // §314.4(h) — Incident response
  q7_1: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'The written incident response plan, dated and distributed to the response team.',
    consequence:
      '§314.4(h) requires a *written* incident response plan. Its absence is binary and immediately provable — and it is what turns the first hour of an incident into deciding who to call.',
  },
  q7_2: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'A dated tabletop exercise record with the findings and the fixes made.',
    consequence:
      'An untested plan fails on the parts nobody checked — contact lists, escalation paths — and you have no record of evaluating and revising it, which the Rule expects following a material change or incident.',
  },
  q7_3: {
    owner: 'qualified_individual',
    effort: 'moderate',
    proof: 'The breach-notification procedure with named owners and the notification timeline.',
    consequence:
      '§314.4(h)(4) requires the plan to address internal and external communications, and §314.4(j) obliges FTC notification for events reaching 500 consumers within 30 days. Improvising those deadlines compounds the original incident.',
  },
  q7_4: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: "A named incident response team roster with each member's role and decision authority.",
    consequence:
      '§314.4(h)(3) requires the plan to define roles, responsibilities, and levels of decision-making authority. Unnamed roles mean containment waits for the owner to be reachable.',
  },
  q7_5: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'An incident log with entries for handling and resolution (empty is fine if dated and maintained).',
    consequence:
      '§314.4(h)(6) requires documentation and reporting of security events and the response to them. No log means no evidence the element was ever operating.',
  },

  // §314.4(e)(1) — Personnel / training
  q8_1: {
    owner: 'hr_training',
    effort: 'moderate',
    proof: 'A training completion report covering all staff, with dates.',
    consequence:
      '§314.4(e)(1) requires security awareness training for personnel. Completion records are the evidence — training that happened but was not recorded does not satisfy the element.',
  },
  q8_2: {
    owner: 'hr_training',
    effort: 'moderate',
    proof: 'Phishing simulation results with the follow-up training assigned.',
    consequence:
      'The Rule expects training to be updated to reflect current risks. Without simulation results you cannot show the program is current rather than a one-time slide deck.',
  },
  q8_3: {
    owner: 'hr_training',
    effort: 'quick',
    proof: 'An onboarding checklist item requiring security training before system access is granted.',
    consequence:
      'Granting DMS credentials before any §314.4(e) training creates a documented window of untrained access on every new hire — a pattern, not a one-off.',
  },
  q8_4: {
    owner: 'hr_training',
    effort: 'quick',
    proof: 'Retained training records showing who completed what, and when.',
    consequence:
      'Records are how the §314.4(e)(1) element is proven. An unverifiable training program is treated the same as no training program.',
  },
  q8_5: {
    owner: 'hr_training',
    effort: 'quick',
    proof: 'The training curriculum showing social-engineering and pretexting content.',
    consequence:
      '§314.4(e)(1) expects training to reflect the risks the dealership actually faces, and pretexting — fake lenders, fake vendors, fake buyers — is the attack most exercised against a store. A curriculum that omits it leaves the likeliest threat untrained and undocumented.',
  },

  // §314.4(d) — Testing and monitoring
  q9_1: {
    owner: 'qualified_individual',
    effort: 'project',
    proof: 'The annual penetration test report from a qualified third party.',
    consequence:
      '§314.4(d)(2) requires annual penetration testing unless you operate effective continuous monitoring. Doing neither fails the element outright — the Rule offers a choice between them, not an exemption from both.',
  },
  q9_2: {
    owner: 'it_msp',
    effort: 'moderate',
    proof: 'Vulnerability scan reports at least every six months, with remediation notes.',
    consequence:
      '§314.4(d)(2) sets semi-annual vulnerability assessments as the floor absent continuous monitoring. Scan dates are among the easiest facts in the program for an examiner to verify.',
  },
  q9_3: {
    owner: 'it_msp',
    effort: 'project',
    proof: 'Monitoring/SIEM configuration plus a sample alert review.',
    consequence:
      'Continuous monitoring is the §314.4(d)(2) alternative to annual pen testing plus semi-annual scans. Claiming it without evidence is worse than not claiming it.',
  },
  q9_4: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: 'A vulnerability tracker showing findings with owners and target dates.',
    consequence:
      'The Rule requires safeguards to be tested *and the results acted on*. Findings carried unremediated across reports demonstrate a known, unaddressed deficiency.',
  },
  q9_5: {
    owner: 'qualified_individual',
    effort: 'quick',
    proof: "The QI's dated review of test results and the remediation direction given.",
    consequence:
      'Test results that never reach the accountable owner cannot inform the §314.4(i) report to the board, so a gap here quietly breaks the reporting element too.',
  },
};

/** Coordination for a requirement code, falling back honestly rather than fabricating. */
export function getCoordination(code: string): Coordination {
  return COORDINATION_BY_CODE[code] ?? COORDINATION_FALLBACK;
}

/**
 * Planning horizon for a piece of remediation — "what can be done in the next 30 days".
 *
 * Deterministic matrix over (priority, effort). EFFORT DOMINATES, deliberately: 23 of the 45
 * requirements carry the `critical` scoring weight, so sequencing on urgency alone puts ~31
 * items in the first 30 days, which is not a plan — it is the same undifferentiated gap list
 * with a deadline on it. Promising more than a month can hold is exactly how a remediation
 * roadmap loses credibility on first review.
 *
 * So the 30-day bucket holds only work that is BOTH urgent and genuinely short (under a day),
 * which is also the right behavioural bias: a store that closes fifteen small items in month
 * one keeps going. Nothing critical is ever parked past 60 days.
 */
export function horizonFor(priority: TaskPriority, effort: Effort): Horizon {
  if (priority === 'critical') return effort === 'quick' ? 30 : 60;
  if (priority === 'high') return effort === 'quick' ? 30 : 90;
  return effort === 'quick' ? 60 : 90;
}

export const HORIZON_LABEL: Record<Horizon, string> = {
  30: 'Next 30 days',
  60: 'Days 31–60',
  90: 'Days 61–90',
};
