// Incident Response Plan model — the deterministic content for the §314.4(h) written IRP
// (PRD #23). Pure and dependency-light (mirrors shared/security-architecture.ts): no LLM, no
// DB, no network, no dates. Imported by both runtimes and the client, so imports are bare,
// runtime-neutral, and explicitly `.ts`.
//
// DETERMINISM / GROUNDING (the compliance non-negotiable): the seven §314.4(h) elements are
// authored, prescriptive plan content — what the dealership's plan REQUIRES, never a claim that
// a control is already in place. The Incident Response Lead is grounded in the dealership's real
// Qualified Individual; the "current readiness" posture is derived deterministically from the
// dealer's saved section-7 answers (shared/derivation.ts) and states the honest status of each
// control, with its §314.4 citation and triggering answer. No conclusion is generated by an LLM.

import { REQUIREMENT_CATALOG } from './requirements.ts';
import {
  deriveAssessmentFromAnswers,
  joinControlsWithRequirements,
  type DerivedGap,
  type ControlWithRequirement,
} from './derivation.ts';
import { isExemptUnder5000 } from './applicability.ts';
import type { AnswerValue } from './controls.ts';

/** The IRP element citation — 16 CFR §314.4(h). */
export const IRP_CITATION = '§314.4(h)';
/** The Safeguards section whose answers describe the dealer's IRP readiness. */
export const IRP_SECTION = 7;
/** The operative FTC breach-notification obligation — 16 CFR §314.4(j) (effective May 13, 2024
 *  per §314.5). §314.5 is only the effective-date section and imposes no duty itself. */
export const BREACH_NOTICE_CITATION = '§314.4(j)';

/** Minimal structural dealership shape — DealershipInfo (pdf-generator) and a Drizzle row both
 *  satisfy it, so this module never imports a runtime-specific type. */
export interface IrpDealership {
  name: string;
  qualifiedIndividual: string;
  qiEmail: string;
  consumerCount?: number | null;
}

/** The seven required elements of a §314.4(h) incident response plan, in order. */
export type IrpElementKey = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'h7';

export interface IrpElement {
  key: IrpElementKey;
  /** The most specific §314.4(h) subsection this element satisfies. */
  citation: string;
  title: string;
  /** Authored, prescriptive plan paragraphs (deterministic). */
  paragraphs: string[];
}

export interface IrpReadiness {
  /** Section-7 weighted percentage (0-100), same scale as the Dashboard/WISP. */
  score: number;
  /** Section-7 controls confirmed fully in place. */
  confirmed: ControlWithRequirement[];
  /** Open section-7 gaps (each carries §314.4 citation + triggering answer). */
  gaps: DerivedGap[];
  criticalGaps: DerivedGap[];
}

export interface IrpPlan {
  /** Exactly seven elements, ordered h1..h7 — the §314.4(h) required elements. */
  elements: IrpElement[];
  /** The §314.4(j) FTC breach-notification callout. */
  breachNotice: string[];
  /** The Incident Response Lead, grounded in the dealership's Qualified Individual. */
  lead: { name: string; email: string; designated: boolean };
  /** Honest current readiness, derived from saved section-7 answers. */
  readiness: IrpReadiness;
  /** True when the profile qualifies for the §314.6(a) exemption (which lifts §314.4(h)). */
  isExempt: boolean;
}

function buildLead(dealership: IrpDealership): IrpPlan['lead'] {
  const name = (dealership.qualifiedIndividual ?? '').trim();
  const email = (dealership.qiEmail ?? '').trim();
  return { name, email, designated: name.length > 0 };
}

function buildElements(lead: IrpPlan['lead']): IrpElement[] {
  const roleSentence = lead.designated
    ? `The Qualified Individual, ${lead.name}${lead.email ? ` (${lead.email})` : ''}, serves as the ` +
      'Incident Response Lead, with authority to declare a security event, direct containment, engage ' +
      'outside counsel or forensic assistance, and approve customer, regulator, and law-enforcement notifications.'
    : 'No Qualified Individual is currently designated. 16 CFR §314.4(a) requires one, and this Incident ' +
      'Response Lead role — with authority to declare a security event and approve notifications — must be ' +
      'assigned before an incident occurs.';

  return [
    {
      key: 'h1',
      citation: '§314.4(h)(1)',
      title: 'Goals of the Plan',
      paragraphs: [
        'The goals of this plan are to enable the dealership to respond promptly and effectively to any ' +
          'security event affecting customer information; to limit harm to customers and to the dealership; ' +
          'to restore the confidentiality, integrity, and availability of affected systems and data; and to ' +
          "meet the dealership's legal and regulatory notification obligations.",
      ],
    },
    {
      key: 'h2',
      citation: '§314.4(h)(2)',
      title: 'Internal Processes for Responding to a Security Event',
      paragraphs: [
        'On discovery of a suspected security event, staff report it immediately to the Incident Response ' +
          'Lead, who triages the report and, if warranted, declares an incident.',
        'The response then follows defined phases: (1) identification and triage; (2) containment to stop ' +
          'ongoing unauthorized access or data loss; (3) eradication of the underlying cause; (4) recovery ' +
          'and restoration of affected systems from a known-good state; and (5) closure once the event is ' +
          'resolved, documented, and any required notifications are complete.',
      ],
    },
    {
      key: 'h3',
      citation: '§314.4(h)(3)',
      title: 'Roles, Responsibilities & Levels of Decision-Making Authority',
      paragraphs: [
        roleSentence,
        'The incident response team supports the Lead across information technology and systems, legal and ' +
          'compliance, communications, and executive decision-making. Each role and its backup are documented ' +
          'so the response continues without interruption, and the authority to declare an incident and to ' +
          'approve external notifications rests with the Incident Response Lead in consultation with leadership.',
      ],
    },
    {
      key: 'h4',
      citation: '§314.4(h)(4)',
      title: 'Internal & External Communications and Information Sharing',
      paragraphs: [
        'Internal communications keep leadership, affected departments, and the response team informed on a ' +
          'need-to-know basis throughout the incident.',
        'External communications and information sharing — with affected customers, the Federal Trade ' +
          'Commission, law enforcement, insurers, and affected service providers — are coordinated by the ' +
          'Incident Response Lead and follow the breach-notification timeline below. All external statements ' +
          'are reviewed and approved before release to avoid inaccurate or premature disclosure.',
      ],
    },
    {
      key: 'h5',
      citation: '§314.4(h)(5)',
      title: 'Remediation of Identified Weaknesses',
      paragraphs: [
        'Weaknesses in information systems and controls identified during detection and response are ' +
          'remediated. The Lead records each identified weakness, assigns an owner and a target date, tracks ' +
          "it to closure, and feeds material findings into the dealership's written risk assessment (§314.4(b)).",
      ],
    },
    {
      key: 'h6',
      citation: '§314.4(h)(6)',
      title: 'Documentation & Reporting of Events and Response Activities',
      paragraphs: [
        'Every security event and the response to it are documented in an incident log: what happened, when ' +
          'it was discovered, the systems and data involved, the actions taken, the notifications made, and ' +
          'the resolution. The Lead reports material events to leadership and the board and retains the ' +
          'documentation as the evidence trail regulators expect.',
      ],
    },
    {
      key: 'h7',
      citation: '§314.4(h)(7)',
      title: 'Post-Incident Evaluation & Revision',
      paragraphs: [
        'After each significant incident, the Lead conducts a post-incident review to evaluate the ' +
          'effectiveness of the response, capture lessons learned, and revise this plan and the ' +
          "dealership's safeguards accordingly. This plan is also reviewed at least annually and after " +
          'material changes to operations, systems, or vendors, and is exercised through a tabletop test.',
      ],
    },
  ];
}

function buildBreachNotice(): string[] {
  return [
    'Under 16 CFR §314.4(j) (effective May 13, 2024 per §314.5), the dealership must notify the Federal ' +
      'Trade Commission as soon as possible, and no later than 30 days after discovery, of a notification ' +
      'event — the unauthorized acquisition of unencrypted customer information involving at least 500 ' +
      "consumers. Notice is filed through the FTC's online reporting portal and includes the details the Rule requires.",
    'This obligation applies regardless of the dealership’s size and is in addition to any state ' +
      'breach-notification laws, which may set their own deadlines and content. The Incident Response Lead ' +
      'determines whether an event meets this threshold and is responsible for filing on time.',
  ];
}

/**
 * Build the full, deterministic Incident Response Plan. Pure: same inputs -> byte-identical model
 * (no dates, no randomness, no I/O). The seven elements are authored plan content; the readiness
 * block is derived from the saved section-7 answers so it can never disagree with the Dashboard.
 */
export function buildIncidentResponsePlan(
  dealership: IrpDealership,
  answers: Record<string, AnswerValue> | null | undefined,
): IrpPlan {
  const lead = buildLead(dealership);
  const section7 = REQUIREMENT_CATALOG.filter((r) => r.section === IRP_SECTION);
  const assessment = deriveAssessmentFromAnswers(section7, answers);
  const derived = assessment.sections.find((s) => s.section === IRP_SECTION);
  const joined = joinControlsWithRequirements(section7, answers);

  return {
    elements: buildElements(lead),
    breachNotice: buildBreachNotice(),
    lead,
    readiness: {
      score: derived?.score ?? 0,
      confirmed: joined.filter((c) => c.status === 'implemented'),
      gaps: derived?.gaps ?? [],
      criticalGaps: derived?.criticalGaps ?? [],
    },
    isExempt: isExemptUnder5000({ consumerCount: dealership.consumerCount ?? null }),
  };
}
