// Policy templates — the deterministic content for the §314.4(c) written policies (PRD #22).
// Pure and dependency-light (mirrors shared/incident-response.ts / security-architecture.ts): no
// LLM, no DB, no network, no dates. Imported by both runtimes and the client, so imports are
// bare, runtime-neutral, and explicitly `.ts`.
//
// DETERMINISM / GROUNDING (the compliance non-negotiable): each policy's clauses are authored,
// prescriptive statements — what the policy REQUIRES — headed by the §314.4(c) subsection the
// policy fulfills. The "current posture" is derived deterministically from the dealer's saved
// answers to the related questionnaire controls; it reports each control's HONEST status (with its
// own §314.4 citation + triggering answer) and NEVER claims a control is in place when the answer
// says otherwise. No clause, citation, or status is generated by an LLM.

import { REQUIREMENT_CATALOG, type Requirement } from './requirements.ts';
import { joinControlsWithRequirements, isGapStatus } from './derivation.ts';
import { ASSESSMENT_DISCLAIMER } from './security-architecture.ts';
import type { AnswerValue, ControlStatus } from './controls.ts';

export type PolicyType =
  | 'access_control'
  | 'encryption'
  | 'mfa'
  | 'disposal'
  | 'change_management';

/** Ordered list of the generatable policy types (drives the UI picker + integrity tests). */
export const POLICY_TYPES: PolicyType[] = [
  'access_control',
  'encryption',
  'mfa',
  'disposal',
  'change_management',
];

export interface PolicyClause {
  heading: string;
  body: string;
}

export interface PolicyDefinition {
  policyType: PolicyType;
  title: string;
  /** The §314.4(c) subsection this policy fulfills (grounded in the Rule text). */
  citation: string;
  /** generated_documents.docType for this policy's PDF. */
  docType: string;
  /** One-line statement of what the policy governs. */
  purpose: string;
  /** Primary questionnaire code used to link the policies row's requirementId. Undefined when the
   *  Rule subsection has no direct questionnaire control (change management, §314.4(c)(7)). */
  primaryCode?: string;
  /** Questionnaire codes whose saved answers evidence the dealer's honest current posture. */
  groundingCodes: string[];
  /** Authored, normative policy statements (deterministic — NOT generated). */
  clauses: PolicyClause[];
}

export const POLICY_DEFINITIONS: Record<PolicyType, PolicyDefinition> = {
  access_control: {
    policyType: 'access_control',
    title: 'Access Control Policy',
    citation: '§314.4(c)(1)',
    docType: 'policy_access_control',
    purpose:
      'Govern who may access systems and customer nonpublic personal information (NPI), restricting ' +
      'access to what each role requires.',
    primaryCode: 'q4_2',
    groundingCodes: ['q4_2', 'q4_3', 'q4_5'],
    clauses: [
      {
        heading: 'Least Privilege',
        body:
          'Access to systems and customer NPI is limited to what each user’s role requires. Broad or ' +
          'default administrative access is not granted.',
      },
      {
        heading: 'Role-Based Authorization',
        body:
          'Access is granted through defined roles, authorized by the Qualified Individual or a delegate, ' +
          'and recorded so every grant is attributable.',
      },
      {
        heading: 'Provisioning & Revocation',
        body:
          'Access is provisioned only after authorization and revoked immediately when an employee is ' +
          'terminated or changes roles, following a documented procedure.',
      },
      {
        heading: 'Privileged-Access Monitoring',
        body:
          'Privileged and administrative access to NPI systems is monitored and logged so that activity ' +
          'can be reviewed and alerted on.',
      },
      {
        heading: 'Periodic Review',
        body:
          'User access rights are reviewed at least quarterly, and entitlements no longer needed are removed.',
      },
    ],
  },
  encryption: {
    policyType: 'encryption',
    title: 'Encryption Policy',
    citation: '§314.4(c)(3)',
    docType: 'policy_encryption',
    purpose:
      'Protect customer NPI at rest and in transit through encryption, so intercepted or stolen data is ' +
      'unusable to an attacker.',
    primaryCode: 'q5_1',
    groundingCodes: ['q5_1', 'q5_2', 'q5_3', 'q5_4', 'q5_5'],
    clauses: [
      {
        heading: 'Encryption at Rest',
        body:
          'All stored customer NPI is encrypted using a strong, industry-standard algorithm such as AES-256.',
      },
      {
        heading: 'Encryption in Transit',
        body:
          'All transmission of customer NPI uses TLS 1.2 or higher; plaintext transmission of NPI is prohibited.',
      },
      {
        heading: 'Key Management',
        body:
          'Encryption keys are stored securely, access to them is restricted, and they are rotated on a ' +
          'defined schedule.',
      },
      {
        heading: 'Email & Mobile Devices',
        body:
          'Email containing NPI is encrypted or sent through a secure portal, and any mobile device that ' +
          'accesses or stores NPI uses full-device encryption.',
      },
      {
        heading: 'Exceptions',
        body:
          'Where encryption of customer information is infeasible, the Qualified Individual must review and ' +
          'approve effective alternative compensating controls in writing.',
      },
    ],
  },
  mfa: {
    policyType: 'mfa',
    title: 'Multi-Factor Authentication Policy',
    citation: '§314.4(c)(5)',
    docType: 'policy_mfa',
    purpose:
      'Require multi-factor authentication (MFA) for access to systems holding customer NPI, the single ' +
      'most effective barrier to account takeover.',
    primaryCode: 'q4_1',
    groundingCodes: ['q4_1'],
    clauses: [
      {
        heading: 'MFA Requirement',
        body:
          'Multi-factor authentication is required for every user and system accessing any information ' +
          'system that stores or processes customer NPI.',
      },
      {
        heading: 'Accepted Factors',
        body:
          'MFA combines at least two independent factors (something you know, have, or are); SMS one-time ' +
          'codes are used only where a stronger authenticator is not available.',
      },
      {
        heading: 'Enforcement & Exceptions',
        body:
          'MFA is enforced by system configuration. Any exception is temporary, documented, and approved by ' +
          'the Qualified Individual with a compensating control.',
      },
      {
        heading: 'Monitoring',
        body:
          'Failed and anomalous authentication attempts are logged and reviewed as part of access monitoring.',
      },
    ],
  },
  disposal: {
    policyType: 'disposal',
    title: 'Data Retention & Secure Disposal Policy',
    citation: '§314.4(c)(6)',
    docType: 'policy_disposal',
    purpose:
      'Limit how long customer NPI is retained and ensure it is securely disposed of when no longer needed, ' +
      'reducing avoidable breach exposure.',
    primaryCode: 'q3_2',
    groundingCodes: ['q3_2', 'q3_4'],
    clauses: [
      {
        heading: 'Retention Schedule',
        body:
          'A written retention schedule defines how long each type of customer NPI is kept, based on business ' +
          'and legal need; NPI is not retained longer than necessary.',
      },
      {
        heading: 'Periodic Retention Review',
        body:
          'The data retention policy is reviewed periodically, and NPI that has reached the end of its ' +
          'retention period is identified for disposal.',
      },
      {
        heading: 'Secure Disposal',
        body:
          'Electronic NPI is securely wiped or the media destroyed, and paper NPI is shredded, so disposed ' +
          'information cannot be reconstructed.',
      },
      {
        heading: 'Third-Party Disposal',
        body:
          'Vendors that dispose of NPI on the dealership’s behalf are contractually bound to equivalent secure ' +
          'disposal practices and provide evidence of destruction.',
      },
      {
        heading: 'Recordkeeping',
        body: 'Disposal activities are recorded so the dealership can evidence that NPI was destroyed securely.',
      },
    ],
  },
  change_management: {
    policyType: 'change_management',
    title: 'Change Management Policy',
    citation: '§314.4(c)(7)',
    docType: 'policy_change_management',
    // No questionnaire control maps directly to §314.4(c)(7); requirementId is therefore left
    // unlinked and posture is grounded in the related change-triggered reassessment control (q2_5).
    purpose:
      'Govern changes to information systems that handle customer NPI, so security is evaluated before ' +
      'changes are made and new risks are caught early.',
    groundingCodes: ['q2_5'],
    clauses: [
      {
        heading: 'Scope',
        body:
          'This policy covers additions, replacements, and significant modifications to systems, applications, ' +
          'and services that store, process, or transmit customer NPI.',
      },
      {
        heading: 'Request & Approval',
        body:
          'Changes are requested, reviewed, and approved through a documented process before implementation; ' +
          'emergency changes are approved retroactively and documented.',
      },
      {
        heading: 'Security Review & Testing',
        body:
          'Each change is evaluated for its security impact and tested before it reaches production, including ' +
          'assessment of externally developed applications.',
      },
      {
        heading: 'Change-Triggered Risk Reassessment',
        body:
          'Significant changes to NPI systems trigger a targeted risk reassessment, feeding the dealership’s ' +
          'written risk assessment (§314.4(b)(2)).',
      },
      {
        heading: 'Documentation & Rollback',
        body:
          'Every change is documented with its approver, date, and a rollback plan so the dealership can ' +
          'recover if a change causes a problem.',
      },
    ],
  },
};

export interface PolicyPostureItem {
  requirement: Requirement;
  status: ControlStatus;
  triggeringAnswer: AnswerValue;
  isGap: boolean;
}

export interface PolicyPosture {
  confirmed: PolicyPostureItem[];
  gaps: PolicyPostureItem[];
}

/** The dealer's saved answer for a control, phrased for the reader (grounded in the derived
 *  status). Shared by the plaintext and PDF renderings so the wording can never drift. */
export function policyAnswerLabel(status: ControlStatus): string {
  if (status === 'implemented') return 'Current answer: Yes';
  if (status === 'partial') return 'Current answer: Partially in place';
  if (status === 'not_implemented') return 'Current answer: No';
  return 'Not answered yet';
}

/**
 * Derive the honest current posture for a policy from the saved answers. Pure: joins this policy's
 * grounding codes with the global catalog + the answer map, splitting into controls confirmed in
 * place vs. open gaps. Never guesses an unanswered control as a negative claim — an `unknown`
 * status is an open item ("Not answered yet"), not a false "implemented".
 */
export function buildPolicyPosture(
  def: PolicyDefinition,
  answers: Record<string, AnswerValue> | null | undefined,
): PolicyPosture {
  const catalog = REQUIREMENT_CATALOG.filter((r) => def.groundingCodes.includes(r.code));
  const items: PolicyPostureItem[] = joinControlsWithRequirements(catalog, answers).map((c) => ({
    requirement: c.requirement,
    status: c.status,
    triggeringAnswer: c.triggeringAnswer,
    isGap: isGapStatus(c.status),
  }));
  return {
    confirmed: items.filter((i) => !i.isGap),
    gaps: items.filter((i) => i.isGap),
  };
}

/** Minimal structural dealership shape for the plaintext rendering. */
export interface PolicyDealership {
  name: string;
  qualifiedIndividual: string;
  qiEmail: string;
}

/**
 * Render the policy to plain text — the authoritative human-readable content stored on the
 * `policies` row (`content`). Deterministic; the PDF renders the same clauses + posture. Cites the
 * requirement and reflects the dealer's honest posture, so it is safe to store and to unit-test.
 */
export function renderPolicyText(
  def: PolicyDefinition,
  dealership: PolicyDealership,
  answers: Record<string, AnswerValue> | null | undefined,
): string {
  const posture = buildPolicyPosture(def, answers);
  const lines: string[] = [];
  lines.push(def.title.toUpperCase());
  lines.push(`FTC Safeguards Rule ${def.citation} — 16 CFR Part 314`);
  lines.push('');
  lines.push(`Dealership: ${dealership.name || 'Not provided'}`);
  lines.push(
    `Qualified Individual: ${dealership.qualifiedIndividual || 'Not designated'}${
      dealership.qiEmail ? ` (${dealership.qiEmail})` : ''
    }`,
  );
  lines.push('Status: DRAFT — review with counsel and formally adopt before relying on this policy.');
  lines.push('');
  lines.push('PURPOSE');
  lines.push(def.purpose);
  lines.push('');
  lines.push(`This policy implements the safeguard required by 16 CFR ${def.citation}.`);
  lines.push('');
  lines.push('POLICY STATEMENTS');
  def.clauses.forEach((clause, i) => {
    lines.push(`${i + 1}. ${clause.heading}`);
    lines.push(`   ${clause.body}`);
  });
  lines.push('');
  lines.push(`CURRENT POSTURE (${def.citation})`);
  if (posture.confirmed.length === 0 && posture.gaps.length === 0) {
    lines.push('No related self-assessment answers were found for this control area.');
  } else {
    if (posture.confirmed.length > 0) {
      lines.push('Confirmed in place:');
      for (const item of posture.confirmed) {
        lines.push(`- ${item.requirement.title} [${item.requirement.citation}] — ${policyAnswerLabel(item.status)}`);
      }
    }
    if (posture.gaps.length > 0) {
      lines.push('Required — not yet confirmed in place:');
      for (const item of posture.gaps) {
        lines.push(
          `- ${item.requirement.title} [${item.requirement.citation}] — ${policyAnswerLabel(item.status)}`,
        );
      }
      lines.push(
        'These controls are required by the Safeguards Rule but are not yet confirmed in place. Adopting ' +
          'this policy is the first step; implement and evidence each item to close the gap.',
      );
    }
  }
  lines.push('');
  lines.push('DISCLAIMER');
  lines.push(ASSESSMENT_DISCLAIMER);
  return lines.join('\n');
}
